/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Thu Apr 24 10:21:50 1997
 */
#ifndef _itemprocs_
#define _itemprocs_
#if __STDC__

extern item *add_to_ilist ( item *i1, item *i2 );
extern item *check_prec ( item *a, int b );
extern item *copy_item ( item *anitem );
extern int length_ilist ( item *i1 );
extern item *new_align ( int n );
extern item *new_henc ( int indent, item *open, item *close, item *body );
extern item *new_hlis ( int indent, char sep[16], item *body );
extern item *new_hsep ( int indent, char sep[16], item *body );
extern item *new_hspa ( int val );
extern item *new_item ( item_type spec_type );
extern item *new_list1 ( item *i1 );
extern item *new_list2 ( item *i1, item *i2 );
extern item *new_list3 ( item *i1, item *i2, item *i3 );
extern item *new_list4 ( item *i1, item *i2, item *i3, item *i4 );
extern item *new_list5 ( item *i1, item *i2, item *i3, item *i4, item *i5 );
extern item *new_list6 ( item *i1, item *i2, item *i3, item *i4, item *i5, item *i6 );
extern item *new_list7 ( item *i1, item *i2, item *i3, item *i4, item *i5, item *i6, item *i7 );
extern item *new_list8 ( item *i1, item *i2, item *i3, item *i4, item *i5, item *i6, item *i7,
                         item *i8 );
extern item *new_list9 ( item *i1, item *i2, item *i3, item *i4, item *i5, item *i6, item *i7,
                         item *i8, item *i9 );
extern item *new_list10 ( item *i1, item *i2, item *i3, item *i4, item *i5, item *i6, item *i7,
                         item *i8, item *i9, item *i10 );
extern item *new_list11 ( item *i1, item *i2, item *i3, item *i4, item *i5, item *i6, item *i7,
                         item *i8, item *i9, item *i10, item *i11 );
extern item *new_list12 ( item *i1, item *i2, item *i3, item *i4, item *i5, item *i6, item *i7,
                         item *i8, item *i9, item *i10, item *i11, item *i12 );
extern item *new_number ( int x );
extern item *new_pos ( item *i, int n );
extern item *new_text ( char *txt );
extern item *new_venc ( int indent, item *open, item *close, item *body );
extern item *new_vlis ( int indent, char sep[16], item *body );
extern item *new_vsep ( int indent, char sep[16], item *body );
extern item *new_vspa ( int val );

#else /* __STDC__ */

extern item *add_to_ilist (/* item *i1, item *i2 */);
extern item *check_prec (/* item *a, int b */);
extern item *copy_item (/* item *anitem */);
extern int length_ilist (/* item *i1 */);
extern item *new_align (/* int n */);
extern item *new_henc (/* int indent, item *open, item *close, item *body */);
extern item *new_hlis (/* int indent, char sep[16], item *body */);
extern item *new_hsep (/* int indent, char sep[16], item *body */);
extern item *new_hspa (/* int val */);
extern item *new_item (/* item_type spec_type */);
extern item *new_list1 (/* item *i1 */);
extern item *new_list2 (/* item *i1, item *i2 */);
extern item *new_list3 (/* item *i1, item *i2, item *i3 */);
extern item *new_list4 (/* item *i1, item *i2, item *i3, item *i4 */);
extern item *new_list5 (/* item *i1, item *i2, item *i3, item *i4, item
                         *i5 */);
extern item *new_list6 (/* item *i1, item *i2, item *i3, item *i4, item
                         *i5, item *i6 */);
extern item *new_list7 (/* item *i1, item *i2, item *i3, item *i4, item
                         *i5, item *i6, item *i7 */);
extern item *new_number (/* int x */);
extern item *new_pos (/* item *i, int n */);
extern item *new_text (/* char *txt */);
extern item *new_venc (/* int indent, item *open, item *close, item *body */);
extern item *new_vlis (/* int indent, char sep[16], item *body */);
extern item *new_vsep (/* int indent, char sep[16], item *body */);
extern item *new_vspa (/* int val */);

#endif /* __STDC__ */
#endif /* _itemprocs_ */
