/*
 * generated by Xtext
 */
package fr.irisa.cairn.model.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MathematicaUiModule extends fr.irisa.cairn.model.ui.AbstractMathematicaUiModule {
	public MathematicaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
