scheduleResult["computeDistances", 
 {{"absValue", {"i", "j", "N", "M"}, sched[{1, 0, 0, 0}, 3]}, 
  {"d", {"j", "N", "M"}, sched[{0, 1, 0}, 4]}, 
  {"descriptor", {"i", "N", "M"}, sched[{1, 0, 0}, 0]}, 
  {"diff", {"i", "j", "N", "M"}, sched[{1, 0, 0, 0}, 2]}, 
  {"distances", {"j", "N", "M"}, sched[{0, 1, 0}, 5]}, 
  {"dloc", {"i", "j", "N", "M"}, sched[{1, 0, 0, 0}, 4]}, 
  {"image", {"i", "j", "N", "M"}, sched[{1, 0, 0, 0}, 1]}, 
  {"temp", {"i", "j", "N", "M"}, sched[{1, 0, 0, 0}, 1]}}, {1, 0, 5}]
