#!/bin/sh

SCALA_HOME=/Developer/Scala
JAVA_INCLUDE="$JAVA_HOME/include"
if [ "$OSTYPE" = "darwin" ]; then
	JAVA_INCLUDE="/System/Library/Frameworks/JavaVM.framework/Headers"
fi

# get base dir
if [ "`echo $0 | grep '^/'`" != "" ]; then BASE="$0"; else BASE="$PWD/$0"; fi
BASE="`echo $BASE | sed 's/\/[^/]*$/\//g' | sed 's/\/.\//\//g' | sed 's/\/$//g'`";


##############
if [ "$1" != "c" ]; then

# cleanup
rm src/Vec3.h 2>/dev/null
rm -r "$BASE/bin" 2>/dev/null
mkdir -p "$BASE/bin"

printf "Build:"

# compile scala
printf " Scala"
scalac -d "$BASE/bin" "$BASE/src/"*.scala || exit

# get the class signature (scala lib to remove warning)
printf " header"
javah -classpath "$SCALA_HOME/lib/scala-library.jar:$BASE/bin" -d "$BASE/src" Vec3 CudaDP || exit

# compile C library in the classpath
printf " C"
gcc -I"$JAVA_INCLUDE" -shared "$BASE/src/Vec3.c" -o "$BASE/bin/libVec3.jnilib" || exit

fi
##############

gcc -I"$JAVA_INCLUDE" -shared "$BASE/src/CudaDP.c" -o "$BASE/bin/libCudaDP.jnilib" || exit

printf ".\n"
# and execute
scala -cp "$BASE/bin" Toy

# java -Djava.library.path=bin -cp /Developer/Scala/lib/scala-library.jar:bin Toy
# javap on the .class file -> get text
# javah on the .class file -> get header file
