/* Generated: 25/4/2010 at 16:2:2 */
/* Code generated by MMAlpha code generator version 0.2.6 (02/02/2001 11:35) FQ */

#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <assert.h>
 
 
 

#define min(a,b) ((a) > (b) ? (b) : (a))
#define max(a,b) ((a) > (b) ? (a) : (b))
#define power(a, i) ((a)^(i))
static int rfloor (int a, int b) {
  assert (b>0);
  return ((a<0) ? ((a+1)/b)-1 : a/b);
}
static int rceil (int a, int b) {
  assert (b>0);
  return ((a>0) ?  ((a-1)/b)+1 : a/b);
}

void fir(int* _x, int* _w, int* _y) {
  /* Aliases for all variables */
#define x(i) _x[(i)]
#define w(k) _w[(-1 + (k))]
#define y(i) _y[(-3 + (i))]
#define YLOC(t, p) _YLOC[(-12 + 4*(p) + (t))]
#define outy(t, p) y(p)
   
  /* Allocate memory for local variables */
  int * _YLOC = (int *) malloc(sizeof(int)*(32));
  
   
  /* Loop variables */
  int i;
  int p;
  int t;
   
  /* A few loops */
  t = 0;
  for (p = 3; p <= 10; ++p) {
    YLOC(t, p) = 0;
  }
  for (t = 1; t <= 3; ++t) {
    for (p = 3; p <= 10; ++p) {
      YLOC(t, p) = (YLOC((-1 + t), p) + (w(t) * x((p + -t))));
    }
  }
  t = 4;
  for (p = 3; p <= 10; ++p) {
    outy(t, p) = YLOC(3, p);
  }
   
  /* Clean up local variables' memory */
  /* Commented out because it was crashing at run time*/
  /*
  free(_YLOC);
  
  */
  /* And finally undef aliases */
#undef x
#undef w
#undef y
#undef YLOC
#undef outy
}
 
int main (void) {
#define x(i) _x[(i)]
#define w(k) _w[(-1 + (k))]
#define y(i) _y[(-3 + (i))]
  int * _x = (int *) malloc(sizeof(int)*(11));
  int * _w = (int *) malloc(sizeof(int)*(3));
  int * _y = (int *) malloc(sizeof(int)*(8));
  int i;
  int k;
   FILE   *file_x=fopen("stimx.txt","w"); 
   FILE   *file_w=fopen("stimw.txt","w"); 
   FILE   *file_y=fopen("stimy.txt","w"); 
  for (i = 0; i <= 10; ++i) {
    fprintf(stdout, "x[%i]?", i);
    fscanf(stdin, "%i", &(x(i)));
    fprintf(file_x,"x[%i]=", i);
    fprintf(file_x,"%i\n", (x(i)));
  }
  for (k = 1; k <= 3; ++k) {
    fprintf(stdout, "w[%i]?", k);
    fscanf(stdin, "%i", &(w(k)));
    fprintf(file_w,"w[%i]=", k);
    fprintf(file_w,"%i\n", (w(k)));
  }
  fir(_x, _w, _y);
  for (i = 3; i <= 10; ++i) {
    fprintf(stdout, "y[%i]=%i\n", i, y(i));
    fprintf(file_y,"y[%i]=%i\n", i, y(i));
  }
  fclose(file_x);
  fclose(file_w);
  fclose(file_y);
  free(_x);
  free(_w);
  free(_y);
#undef x
#undef w
#undef y
   exit(0);
}
