/* Generated: 22/4/2003 at 18:52:52 */
/* Code generated by MMAlpha code generator version 0.2.6 (02/02/2001 11:35) FQ */

#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <assert.h>
 
 

#define min(a,b) ((a) > (b) ? (b) : (a))
#define max(a,b) ((a) > (b) ? (a) : (b))
#define power(a, i) ((a)^(i))
static int rfloor (int a, int b) {
  assert (b>0);
  return ((a<0) ? ((a+1)/b)-1 : a/b);
}
static int rceil (int a, int b) {
  assert (b>0);
  return ((a>0) ?  ((a-1)/b)+1 : a/b);
}

void SimpleEx(float* _a, float* _c) {
  /* aliases for all variables */
#define a(n) _a[(-1 + (n))]
#define c(n) _c[(-1 + (n))]
#define A(t) _A[(-2 + (t))]
#define outc(t) c((-2 + t))
   
  /* allocate memory for local variables */
  float * _A = (float *) malloc(sizeof(float)*(10));
  
   
  /* loops variables */
  int n;
  int t;
   
  /* a few loops */
  t = 2;
  A(t) = (a((-1 + t)) * a((-1 + t)));
  for (t = 3; t <= 11; ++t) {
    A(t) = (a((-1 + t)) * a((-1 + t)));
    outc(t) = A((-1 + t));
  }
  t = 12;
  outc(t) = A((-1 + t));
   
  /* clean up local variables' memory */
  /* commented out because it was crashing at run time*/
  /*
  free(_A);
  
  */
  /* and finally undef aliases */
#undef a
#undef c
#undef A
#undef outc
}
 
int main (void) {
#define a(n) _a[(-1 + (n))]
#define c(n) _c[(-1 + (n))]
  float * _a = (float *) malloc(sizeof(float)*(10));
  float * _c = (float *) malloc(sizeof(float)*(10));
  int n;
   
  for (n = 1; n <= 10; ++n) {
    fprintf(stdout, "a[%i]?", n);
    fscanf(stdin, "%f", &(a(n)));
     
  }
  SimpleEx(_a, _c);
  for (n = 1; n <= 10; ++n) {
    fprintf(stdout, "c[%i]=%f\n", n, c(n));
     
  }
   
  free(_a);
  free(_c);
#undef a
#undef c
   exit(0);
}
