/* Generated: 27/12/2007 at 17:53:53 */
/* Code generated by MMAlpha code generator version 0.2.6 (02/02/2001 11:35) FQ */

#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <assert.h>
#include "mex.h" 
 
 

#define min(a,b) ((a) > (b) ? (b) : (a))
#define max(a,b) ((a) > (b) ? (a) : (b))
#define power(a, i) ((a)^(i))
static int rfloor (int a, int b) {
  assert (b>0);
  return ((a<0) ? ((a+1)/b)-1 : a/b);
}
static int rceil (int a, int b) {
  assert (b>0);
  return ((a>0) ?  ((a-1)/b)+1 : a/b);
}

void prodVect(double* _a, double* _b, double* _c) {
  /* Aliases for all variables */
#define a(i, j) _a[(3*(j) + -4 + (i))]
#define b(i) _b[(-1 + (i))]
#define c(i) _c[(-1 + (i))]
#define C(t, p) _C[(-4 + 4*(p) + (t))]
#define outc(t, p) c(p)
   
  /* Allocate memory for local variables */
  double * _C = (double *) malloc(sizeof(double)*(12));
  
   
  /* Loop variables */
  int i;
  int p;
  int t;
   
  /* A few loops */
  t = 0;
  for (p = 1; p <= 3; ++p) {
    C(t, p) = 0;
  }
  for (t = 1; t <= 3; ++t) {
    for (p = 1; p <= 3; ++p) {
      C(t, p) = (C((-1 + t), p) + (a(p, t) * b(t)));
    }
  }
  t = 4;
  for (p = 1; p <= 3; ++p) {
    outc(t, p) = C(3, p);
  }
   
  /* Clean up local variables' memory */
  /* Commented out because it was crashing at run time*/
  /*
  free(_C);
  
  */
  /* And finally undef aliases */
#undef a
#undef b
#undef c
#undef C
#undef outc
}
 
int main (void) {
#define a(i, j) _a[(3*(j) + -4 + (i))]
#define b(i) _b[(-1 + (i))]
#define c(i) _c[(-1 + (i))]
  double * _a = (double *) malloc(sizeof(double)*(9));
  double * _b = (double *) malloc(sizeof(double)*(3));
  double * _c = (double *) malloc(sizeof(double)*(3));
  int i;
  int j;
   
  for (i = 1; i <= 3; ++i) {
    for (j = 1; j <= 3; ++j) {
      fprintf(stdout, "a[%i, %i]?", i, j);
      fscanf(stdin, "%f", &(a(i, j)));
       
    }
  }
  for (i = 1; i <= 3; ++i) {
    fprintf(stdout, "b[%i]?", i);
    fscanf(stdin, "%f", &(b(i)));
     
  }
  prodVect(_a, _b, _c);
  for (i = 1; i <= 3; ++i) {
    fprintf(stdout, "c[%i]=%f\n", i, c(i));
     
  }
   
  free(_a);
  free(_b);
  free(_c);
#undef a
#undef b
#undef c
   exit(0);
}
