/*
 * generated by Xtext
 */
package fr.irisa.cairn.model;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MathematicaRuntimeModule extends fr.irisa.cairn.model.AbstractMathematicaRuntimeModule {

}
