/* Generated: 23/4/2010 at 8:39:39 */
/* Code generated by MMAlpha code generator version 0.2.6 (02/02/2001 11:35) FQ */

#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <assert.h>
 
 
 

#define min(a,b) ((a) > (b) ? (b) : (a))
#define max(a,b) ((a) > (b) ? (a) : (b))
#define power(a, i) ((a)^(i))
static int rfloor (int a, int b) {
  assert (b>0);
  return ((a<0) ? ((a+1)/b)-1 : a/b);
}
static int rceil (int a, int b) {
  assert (b>0);
  return ((a>0) ?  ((a-1)/b)+1 : a/b);
}

void firr(int* _x, int* _d, int* _res) {
  /* Aliases for all variables */
#define x(n) _x[(-1 + (n))]
#define d(n) _d[(-3 + (n))]
#define res(n) _res[(-3 + (n))]
#define W(t, p) _W[(17*(p) + -51 + (t))]
#define Y(t, p) _Y[(18*(p) + -56 + (t))]
#define E(t, p) _E[(-3 + (p))]
#define outres(t, p) res(p)
   
  /* Allocate memory for local variables */
  int * _W = (int *) malloc(sizeof(int)*(136));
  int * _Y = (int *) malloc(sizeof(int)*(144));
  int * _E = (int *) malloc(sizeof(int)*(8));
  
   
  /* Loop variables */
  int n;
  int p;
  int t;
   
  /* A few loops */
  for (t = 0; t <= 1; ++t) {
    for (p = 3; p <= rfloor(((6 + t)),(2)); ++p) {
      W(t, p) = 0;
    }
  }
  t = 2;
  for (p = 3; p <= 4; ++p) {
    W(t, p) = 0;
  }
  p = 3;
  Y(t, p) = 0;
  for (t = 3; t <= 5; ++t) {
    for (p = rceil(((4 + t)),(2)); p <= rfloor(((6 + t)),(2)); ++p) {
      W(t, p) = 0;
    }
    if ((((4 + t))%2) == 0) {
      p = ((4 + t))/2;
      Y(t, p) = 0;
    }
    for (p = 3; p <= rfloor(((3 + t)),(2)); ++p) {
      Y(t, p) = (Y((-1 + t), p) + (W((4*p + -7 + -t), p) * x((-3 + 3*p + -t))));
    }
  }
  t = 6;
  for (p = 5; p <= 6; ++p) {
    W(t, p) = 0;
  }
  p = 5;
  Y(t, p) = 0;
  p = 4; {
    Y(t, p) = (Y((-1 + t), p) + (W((4*p + -7 + -t), p) * x((-3 + 3*p + -t))));
  }
  p = 3;
  outres(t, p) = Y((-1 + 2*p), p);
  for (t = 7; t <= 11; ++t) {
    for (p = rceil(((4 + t)),(2)); p <= min(8,rfloor(((6 + t)),(2))); ++p) {
      W(t, p) = 0;
    }
    if ((((4 + t))%2) == 0) {
      p = ((4 + t))/2;
      Y(t, p) = 0;
    }
    for (p = rceil(((1 + t)),(2)); p <= rfloor(((3 + t)),(2)); ++p) {
      Y(t, p) = (Y((-1 + t), p) + (W((4*p + -7 + -t), p) * x((-3 + 3*p + -t))));
    }
    if ((((-1 + t))%2) == 0) {
      p = ((-1 + t))/2;
      E(t, p) = ((d(p) - outres(2*p, p)) / 32);
    }
    if (((t)%2) == 0) {
      p = (t)/2;
      outres(t, p) = Y((-1 + 2*p), p);
    }
  }
  for (t = 12; t <= 12; ++t) {
    for (p = rceil(((4 + t)),(2)); p <= 8; ++p) {
      W(t, p) = 0;
    }
    for (p = 9; p <= min(10,rfloor(((6 + t)),(2))); ++p) {
      W(t, p) = (W((-2 + t), (-1 + p)) + (E((-11 + 2*p), (-6 + p)) * x((-2 + -p + t))));
    }
    if ((((4 + t))%2) == 0) {
      p = ((4 + t))/2;
      Y(t, p) = 0;
    }
    for (p = rceil(((1 + t)),(2)); p <= rfloor(((3 + t)),(2)); ++p) {
      Y(t, p) = (Y((-1 + t), p) + (W((4*p + -7 + -t), p) * x((-3 + 3*p + -t))));
    }
    if ((((-1 + t))%2) == 0) {
      p = ((-1 + t))/2;
      E(t, p) = ((d(p) - outres(2*p, p)) / 32);
    }
    if (((t)%2) == 0) {
      p = (t)/2;
      outres(t, p) = Y((-1 + 2*p), p);
    }
  }
  for (t = 13; t <= 16; ++t) {
    for (p = max(9,rceil(((4 + t)),(2))); p <= min(10,rfloor(((6 + t)),(2))); ++p) {
      W(t, p) = (W((-2 + t), (-1 + p)) + (E((-11 + 2*p), (-6 + p)) * x((-2 + -p + t))));
    }
    if ((((4 + t))%2) == 0) {
      p = ((4 + t))/2;
      Y(t, p) = 0;
    }
    for (p = rceil(((1 + t)),(2)); p <= rfloor(((3 + t)),(2)); ++p) {
      Y(t, p) = (Y((-1 + t), p) + (W((4*p + -7 + -t), p) * x((-3 + 3*p + -t))));
    }
    if ((((-1 + t))%2) == 0) {
      p = ((-1 + t))/2;
      E(t, p) = ((d(p) - outres(2*p, p)) / 32);
    }
    if (((t)%2) == 0) {
      p = (t)/2;
      outres(t, p) = Y((-1 + 2*p), p);
    }
  }
  for (t = 17; t <= 19; ++t) {
    for (p = rceil(((1 + t)),(2)); p <= 10; ++p) {
      Y(t, p) = (Y((-1 + t), p) + (W((4*p + -7 + -t), p) * x((-3 + 3*p + -t))));
    }
    if ((((-1 + t))%2) == 0) {
      p = ((-1 + t))/2;
      E(t, p) = ((d(p) - outres(2*p, p)) / 32);
    }
    if (((t)%2) == 0) {
      p = (t)/2;
      outres(t, p) = Y((-1 + 2*p), p);
    }
  }
  t = 20;
  /* dead code removed */
  p = 10;
  outres(t, p) = Y((-1 + 2*p), p);
  t = 21;
  p = 10;
  E(t, p) = ((d(p) - outres(2*p, p)) / 32);
   
  /* Clean up local variables' memory */
  /* Commented out because it was crashing at run time*/
  /*
  free(_W);
  free(_Y);
  free(_E);
  
  */
  /* And finally undef aliases */
#undef x
#undef d
#undef res
#undef W
#undef Y
#undef E
#undef outres
}
 
int main (void) {
#define x(n) _x[(-1 + (n))]
#define d(n) _d[(-3 + (n))]
#define res(n) _res[(-3 + (n))]
  int * _x = (int *) malloc(sizeof(int)*(10));
  int * _d = (int *) malloc(sizeof(int)*(8));
  int * _res = (int *) malloc(sizeof(int)*(8));
  int n;
   FILE   *file_x=fopen("stimx.txt","w"); 
   FILE   *file_d=fopen("stimd.txt","w"); 
   FILE   *file_res=fopen("stimres.txt","w"); 
  for (n = 1; n <= 10; ++n) {
    fprintf(stdout, "x[%i]?", n);
    fscanf(stdin, "%i", &(x(n)));
    fprintf(file_x,"x[%i]=", n);
    fprintf(file_x,"%i\n", (x(n)));
  }
  for (n = 3; n <= 10; ++n) {
    fprintf(stdout, "d[%i]?", n);
    fscanf(stdin, "%i", &(d(n)));
    fprintf(file_d,"d[%i]=", n);
    fprintf(file_d,"%i\n", (d(n)));
  }
  firr(_x, _d, _res);
  for (n = 3; n <= 10; ++n) {
    fprintf(stdout, "res[%i]=%i\n", n, res(n));
    fprintf(file_res,"res[%i]=%i\n", n, res(n));
  }
  fclose(file_x);
  fclose(file_d);
  fclose(file_res);
  free(_x);
  free(_d);
  free(_res);
#undef x
#undef d
#undef res
   exit(0);
}
