/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RNALib */

#ifndef _Included_RNALib
#define _Included_RNALib
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_RNALib_loadParams(JNIEnv *, jobject, jstring);
JNIEXPORT void JNICALL Java_RNALib_loadSequence(JNIEnv *, jobject, jstring);
JNIEXPORT void JNICALL Java_RNALib_clearSequence(JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_RNALib_clearParams(JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_RNALib_termau_1energy(JNIEnv *, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_RNALib_hl_1energy(JNIEnv *, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_RNALib_hl_1energy_1stem(JNIEnv *, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_RNALib_il_1energy(JNIEnv *, jobject, jint, jint, jint, jint);
JNIEXPORT jint JNICALL Java_RNALib_bl_1energy(JNIEnv *, jobject, jint, jint, jint, jint, jint);
JNIEXPORT jint JNICALL Java_RNALib_br_1energy(JNIEnv *, jobject, jint, jint, jint, jint, jint);
JNIEXPORT jint JNICALL Java_RNALib_sr_1energy(JNIEnv *, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_RNALib_sr_1pk_1energy(JNIEnv *, jobject, jchar, jchar, jchar, jchar);
JNIEXPORT jint JNICALL Java_RNALib_dl_1energy(JNIEnv *, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_RNALib_dr_1energy(JNIEnv *, jobject, jint, jint, jint);
JNIEXPORT jint JNICALL Java_RNALib_dli_1energy(JNIEnv *, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_RNALib_dri_1energy(JNIEnv *, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_RNALib_ext_1mismatch_1energy(JNIEnv *, jobject, jint, jint, jint);
JNIEXPORT jint JNICALL Java_RNALib_ml_1mismatch_1energy(JNIEnv *, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_RNALib_ml_1energy(JNIEnv *, jobject);
JNIEXPORT jint JNICALL Java_RNALib_ul_1energy(JNIEnv *, jobject);
JNIEXPORT jint JNICALL Java_RNALib_sbase_1energy(JNIEnv *, jobject);
JNIEXPORT jint JNICALL Java_RNALib_ss_1energy(JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
