/*
* generated by Xtext
*/
package fr.irisa.cairn.model.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class MathematicaTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
