/* Generated: 30/8/2002 at 14:33:33 */
/* Code generated by MMAlpha code generator version 0.2.6 (02/02/2001 11:35) FQ */

#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <assert.h>
 
 

#define min(a,b) ((a) > (b) ? (b) : (a))
#define max(a,b) ((a) > (b) ? (a) : (b))
#define power(a, i) ((a)^(i))
static int rfloor (int a, int b) {
  assert (b>0);
  return ((a<0) ? ((a+1)/b)-1 : a/b);
}
static int rceil (int a, int b) {
  assert (b>0);
  return ((a>0) ?  ((a-1)/b)+1 : a/b);
}

void lx(float* _A, float* _B, float* _X) {
  /* aliases for all variables */
#define A(i, j) _A[(3*(j) + -4 + (i))]
#define B(i) _B[(-1 + (i))]
#define X(i) _X[(-1 + (i))]
#define C(t, p) _C[(3*(p) + -6 + (t))]
#define outX(t, p) X(p)
   
  /* allocate memory for local variables */
  float * _C = (float *) malloc(sizeof(float)*(6));
  
   
  /* loops variables */
  int i;
  int p;
  int t;
   
  /* a few loops */
  t = 2;
  p = 1;
  outX(t, p) = (B(p) / A(p, p));
  t = 3;
  p = 1;
  C(t, p) = (A((-1 + t), p) * outX(2, p));
  t = 4;
  p = 1;
  C(t, p) = (A((-1 + t), p) * outX(2, p));
  p = 2;
  outX(t, p) = ((B(p) - C((-1 + t), (-1 + p))) / A(p, p));
  /* dead code removed */
  t = 5; {
    for (p = (-3 + t); p <= rfloor(((-1 + t)),(2)); ++p) {
      C(t, p) = (C((-1 + t), (-1 + p)) + (A((-p + t), p) * outX(2*p, p)));
    }
    if (((t)%2) == 0) {
      p = (t)/2;
      outX(t, p) = ((B(p) - C((-1 + t), (-1 + p))) / A(p, p));
    }
  }
  t = 6;
  p = 3;
  outX(t, p) = ((B(p) - C((-1 + t), (-1 + p))) / A(p, p));
   
  /* clean up local variables' memory */
  /* commented out because it was crashing at run time*/
  /*
  free(_C);
  
  */
  /* and finally undef aliases */
#undef A
#undef B
#undef X
#undef C
#undef outX
}
 
int main (void) {
#define A(i, j) _A[(3*(j) + -4 + (i))]
#define B(i) _B[(-1 + (i))]
#define X(i) _X[(-1 + (i))]
  float * _A = (float *) malloc(sizeof(float)*(9));
  float * _B = (float *) malloc(sizeof(float)*(3));
  float * _X = (float *) malloc(sizeof(float)*(3));
  int i;
  int j;
   
  for (i = 1; i <= 3; ++i) {
    for (j = 1; j <= i; ++j) {
       
      fscanf(stdin, "%g", &(A(i, j)));
       
    }
  }
  for (i = 1; i <= 3; ++i) {
     
    fscanf(stdin, "%g", &(B(i)));
     
  }
  lx(_A, _B, _X);
  for (i = 1; i <= 3; ++i) {
    fprintf(stdout, "%g\n", X(i));
     
  }
   
  free(_A);
  free(_B);
  free(_X);
#undef A
#undef B
#undef X
   exit(0);
}
