/* Generated: 29/12/2008 at 11:41:41 */
/* Code generated by MMAlpha code generator version 0.2.6 (02/02/2001 11:35) FQ */

#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <assert.h>
 
 
 

#define min(a,b) ((a) > (b) ? (b) : (a))
#define max(a,b) ((a) > (b) ? (a) : (b))
#define power(a, i) ((a)^(i))
static int rfloor (int a, int b) {
  assert (b>0);
  return ((a<0) ? ((a+1)/b)-1 : a/b);
}
static int rceil (int a, int b) {
  assert (b>0);
  return ((a>0) ?  ((a-1)/b)+1 : a/b);
}

void prodVect(int* _a, int* _b, int* _c) {
  /* Aliases for all variables */
#define a(i, j) _a[(2*(j) + -3 + (i))]
#define b(i) _b[(-1 + (i))]
#define c(i) _c[(-1 + (i))]
#define C(t, p) _C[(-3 + 3*(p) + (t))]
#define outc(t, p) c(p)
   
  /* Allocate memory for local variables */
  int * _C = (int *) malloc(sizeof(int)*(6));
  
   
  /* Loop variables */
  int i;
  int p;
  int t;
   
  /* A few loops */
  t = 0;
  for (p = 1; p <= 2; ++p) {
    C(t, p) = 0;
  }
  for (t = 1; t <= 2; ++t) {
    for (p = 1; p <= 2; ++p) {
      C(t, p) = (C((-1 + t), p) + (a(p, t) * b(t)));
    }
  }
  t = 3;
  for (p = 1; p <= 2; ++p) {
    outc(t, p) = C(2, p);
  }
   
  /* Clean up local variables' memory */
  /* Commented out because it was crashing at run time*/
  /*
  free(_C);
  
  */
  /* And finally undef aliases */
#undef a
#undef b
#undef c
#undef C
#undef outc
}
 
int main (void) {
#define a(i, j) _a[(2*(j) + -3 + (i))]
#define b(i) _b[(-1 + (i))]
#define c(i) _c[(-1 + (i))]
  int * _a = (int *) malloc(sizeof(int)*(4));
  int * _b = (int *) malloc(sizeof(int)*(2));
  int * _c = (int *) malloc(sizeof(int)*(2));
  int i;
  int j;
   
  for (i = 1; i <= 2; ++i) {
    for (j = 1; j <= 2; ++j) {
      fprintf(stdout, "a[%i, %i]?", i, j);
      fscanf(stdin, "%i", &(a(i, j)));
       
    }
  }
  for (i = 1; i <= 2; ++i) {
    fprintf(stdout, "b[%i]?", i);
    fscanf(stdin, "%i", &(b(i)));
     
  }
  prodVect(_a, _b, _c);
  for (i = 1; i <= 2; ++i) {
    fprintf(stdout, "c[%i]=%i\n", i, c(i));
     
  }
   
  free(_a);
  free(_b);
  free(_c);
#undef a
#undef b
#undef c
   exit(0);
}
