#
#	This makefile is called to configure a set of variables for the
#	other makefiles.
#
#	See documentation located in doc/Developpers/Compiling-Domlib, and in
#	doc/Domlib
#

#-----------------------------------------------
SHELL	   = /bin/sh

#-----------------------------------------------
#  Here, I set temporarily the Mathematica version used
MMAVERSION = 7.0

#-----------------------------------------------
LDLIB	= ld -r
# LD	= gcc  LD is now defined in Makefile.solaris
CC	 = gcc
#CC	 = /usr/libexec/gcc/darwin/ppc/as
#CC=/soft/purify/purify -cache-dir=/tmp/purify gcc
# since 2001 we should use:
#CC=/usr/local/env/envpurify -cache-dir=/tmp/purify gcc
CFLAGS	= -O3  -g -I$(POLYINCLUDE) $(PRECISIONFLAG) # -Wall -pedantic -ansi
#CFLAGS	= -O3  -g -I$(POLYINCLUDE) -DLINEAR_VALUE_IS_LONGLONG# -Wall -pedantic -ansi
#CFLAGS	= -O3  -g -I$(POLYINCLUDE) -DGNUMP # -Wall -pedantic -ansi
CXX	= g++
YACC	= bison
YFLAGS	= -t -v -d -y 
LEX	= flex
LFLAGS	=
STRIP   = strip

#-----------------------------------------------
# Set some variables, such as MATHLINK and OMEGA directory in OS specific Makefile.
# If any OS specific lib to link, set also MATHEXTRALIBS and MATHEXTRAOBJS.
# Was modified on Sept. 23, 2007, to provide for various versions of Mathematica
# since the information may depend on this.
include ${MMALPHA}/sources/MakeIncludes/Makefile.${OSTYPE}

#----------------------------------------------
MAKEFILES   =  Makefile $(MMALPHA)/sources/MakeIncludes/Makefile.rules $(MMALPHA)/sources/MakeIncludes/Makefile.config $(MMALPHA)/sources/MakeIncludes/Makefile.$(OSTYPE) $(MMALPHA)/sources/MakeIncludes/Makefile.$(OSTYPE).$(MMAVERSION)

#-----------------------------------------------
BINDIR      	= $(MMALPHA)/bin.$(OSTYPE)
LIBDIR		= $(MMALPHA)/lib.$(OSTYPE)
OBJDIR		= Obj.$(OSTYPE)
NEEDBINDIR	= $(BINDIR)/.make
NEEDLIBDIR	= $(LIBDIR)/.make
NEEDOBJDIR	= $(OBJDIR)/.make
SOURCES		= $(MMALPHA)/sources

#-----------------------------------------------
POLYDIR		= $(SOURCES)/polylib-5.22.3

#---------  This is needed for some special cases
#POLYDIR			= /home/trisset/polylib/polylib-5.20.0
POLYINCLUDE	= $(POLYDIR)/include

#POLYOBJS	= $(OBJDIR)/matrix.o $(OBJDIR)/vector.o \
#		  $(OBJDIR)/polyhedron.o $(OBJDIR)/Zpolyhedron.o $(OBJDIR)/Matop.o $(OBJDIR)/Lattice.o $(OBJDIR)/NormalForms.o $(OBJDIR)/SolveDio.o $(OBJDIR)/errors.o 
# Added July 2007
POLYOBJS	= $(OBJDIR)/matrix.o $(OBJDIR)/vector.o \
		  $(OBJDIR)/polyhedron.o $(OBJDIR)/Zpolyhedron.o $(OBJDIR)/Matop.o $(OBJDIR)/Lattice.o $(OBJDIR)/NormalForms.o $(OBJDIR)/SolveDio.o $(OBJDIR)/errors.o $(OBJDIR)/alpha.o $(OBJDIR)/compress_parms.o $(OBJDIR)/matrix_addon.o $(OBJDIR)/matrix_permutations.o $(OBJDIR)/param.o $(OBJDIR)/polyparam.o
POLYXOBJS	= $(OBJDIR)/polyparam.o $(OBJDIR)/alpha.o
POLYMSG		= $(OBJDIR)/errormsg.o

# --------------  Modification here
# Previously, CODEGENOBJS were named codegen.gen.o. Does it matter?

#-----------------------------------------------
CODEGENDIR	= $(SOURCES)/Code_Gen
CODEGENOBJS	= $(OBJDIR)/gen.o $(OBJDIR)/nodeprocs.o

#-----------------------------------------------
#  There is a difference here, as previously, Pretty was used to 
#  obtain Write_C and Code_Gen
#PRETTYDIR	= $(SOURCES)/Write_Alpha
PRETTYDIR	= $(SOURCES)/Pretty
PRETTYOBJS	= $(PRETTYDIR)/$(OBJDIR)/itemprocs.o \
		  $(PRETTYDIR)/$(OBJDIR)/writeitem.o

#-----------------------------------------------
LPSOLVEDIR	= $(SOURCES)/Lp_Solve/lp_solve_2.3

#-----------------------------------------------
OMEGALIB	= $(OMEGADIR)/omega_lib
OMEGABASIC	= $(OMEGADIR)/basic
#-----------------------------------------------


