/* Generated: 1/10/2008 at 19:29:29 */
/* Code generated by MMAlpha code generator version 0.2.6 (02/02/2001 11:35) FQ */

#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <assert.h>
 
 
 

#define min(a,b) ((a) > (b) ? (b) : (a))
#define max(a,b) ((a) > (b) ? (a) : (b))
#define power(a, i) ((a)^(i))
static int rfloor (int a, int b) {
  assert (b>0);
  return ((a<0) ? ((a+1)/b)-1 : a/b);
}
static int rceil (int a, int b) {
  assert (b>0);
  return ((a>0) ?  ((a-1)/b)+1 : a/b);
}

void SimpleEx(float* _a, float* _c) {
  /* Aliases for all variables */
#define a(n) _a[(-1 + (n))]
#define c(n) _c[(-1 + (n))]
#define A1(t, p) _A1[(-2 + (p))]
#define A(t, p) _A[(-1 + (p))]
#define outc(t, p) c(p)
   
  /* Allocate memory for local variables */
  float * _A1 = (float *) malloc(sizeof(float)*(3));
  float * _A = (float *) malloc(sizeof(float)*(3));
  
   
  /* Loop variables */
  int n;
  int p;
  int t;
   
  /* A few loops */
  t = 1;
  for (p = 2; p <= 4; ++p) {
    A1(t, p) = (a((-1 + p)) * a((-1 + p)));
  }
  t = 2;
  for (p = 1; p <= 3; ++p) {
    A(t, p) = A1(1, (1 + p));
  }
  for (p = 1; p <= 3; ++p) {
    outc(t, p) = A1(1, (1 + p));
  }
   
  /* Clean up local variables' memory */
  /* Commented out because it was crashing at run time*/
  /*
  free(_A1);
  free(_A);
  
  */
  /* And finally undef aliases */
#undef a
#undef c
#undef A1
#undef A
#undef outc
}
 
int main (void) {
#define a(n) _a[(-1 + (n))]
#define c(n) _c[(-1 + (n))]
  float * _a = (float *) malloc(sizeof(float)*(3));
  float * _c = (float *) malloc(sizeof(float)*(3));
  int n;
   
  for (n = 1; n <= 3; ++n) {
     
    fscanf(stdin, "%f", &(a(n)));
     
  }
  SimpleEx(_a, _c);
  for (n = 1; n <= 3; ++n) {
    fprintf(stdout, "%f\n", c(n));
     
  }
   
  free(_a);
  free(_c);
#undef a
#undef c
   exit(0);
}
