/* system dotprod1 */

/* C-Code generated by Alpha Code Generator version 1.2 */

#include <math.h>
typedef struct { int value;
		 int computed; } intvar;
typedef struct { int value;
		 int computed; } boolvar;
typedef struct { double value;
		 int computed; } realvar;
double atof();
int    atoi();

#define min(x,y) ((x)<(y)?(x):(y))
#define max(x,y) ((x)>(y)?(x):(y))
#define INFINITY 0x7fffffff

/* parameters */
#define N 5

/* input variables */
char __s[32];
realvar _in[15];
#define in(arg,i)	_in[(arg)+3*(i)-4]

/* output variables */
realvar _out[1];
#define out(arg,i)	_out[(arg)+(i)-7]

/* local variables */
realvar _aux0[15];
#define aux0(arg,i)	_aux0[(arg)+3*(i)-4]
realvar _aux1[5];
#define aux1(arg,i)	_aux1[(arg)+(i)-2]
realvar _aux2[5];
#define aux2(arg,i)	_aux2[(arg)+(i)-3]
realvar _recinter[4];
#define recinter(arg,i)	_recinter[(arg)+(i)-3]
realvar _in_addmul1[15];
#define in_addmul1(arg,i)	_in_addmul1[(arg)+3*(i)-4]
realvar _out_addmul1[5];
#define out_addmul1(arg,i)	_out_addmul1[(arg)+(i)-2]
realvar _aux1_addmul1[5];
#define aux1_addmul1(arg,i)	_aux1_addmul1[(arg)+(i)-2]
realvar _aux2_addmul1[10];
#define aux2_addmul1(arg,i)	_aux2_addmul1[(arg)+2*(i)-3]
realvar _in_mul2[10];
#define in_mul2(arg,i)	_in_mul2[(arg)+2*(i)-3]
realvar _out_mul2[5];
#define out_mul2(arg,i)	_out_mul2[(arg)+(i)-2]
realvar _in_add3[10];
#define in_add3(arg,i)	_in_add3[(arg)+2*(i)-3]
realvar _out_add3[5];
#define out_add3(arg,i)	_out_add3[(arg)+(i)-2]

static double compute_in(arg,i)
int arg,i;
{
  realvar *tmp;
/* printf("Computing: in[%d,%d]\n" ,arg,i); */
  tmp = &(in(arg,i));
  if (!tmp->computed) {
          printf("Input in[%d,%d] =" ,arg,i);
     gets(__s);
     tmp->value = atof(__s);
     tmp->computed = 1;}
  return tmp->value;
}

static double compute_out();

static double compute_aux0();

static double compute_aux1();

static double compute_aux2();

static double compute_recinter();

static double compute_in_addmul1();

static double compute_out_addmul1();

static double compute_aux1_addmul1();

static double compute_aux2_addmul1();

static double compute_in_mul2();

static double compute_out_mul2();

static double compute_in_add3();

static double compute_out_add3();

/* --let equations */
static double compute_aux0(arg,i)
int arg,i;
{
  realvar *tmp;
/* printf("Computing: aux0[%d,%d]\n" ,arg,i); */
  tmp = &(aux0(arg,i));
  if (!tmp->computed) {
          tmp->value = ( arg-2>=0 && -arg+3>=0 && i-1>=0 && -i+N>=0 || 
              i-1==0 && arg-1>=0 && -arg+3>=0 && N-1>=0 )  ? 
            ( compute_in(arg,i) ) : 
         ( arg-1==0 && i-2>=0 && -i+N>=0 )  ? ( compute_recinter(arg,i) ) : 
         ( printf("? case error\n"), exit(-1));
     tmp->computed = 1;}
  return tmp->value;
}

static double compute_in_addmul1(arg,i)
int arg,i;
{
  realvar *tmp;
/* printf("Computing: in_addmul1[%d,%d]\n" ,arg,i); */
  tmp = &(in_addmul1(arg,i));
  if (!tmp->computed) {
          tmp->value = compute_aux0(arg,i);
     tmp->computed = 1;}
  return tmp->value;
}

static double compute_in_mul2(arg,i)
int arg,i;
{
  realvar *tmp;
/* printf("Computing: in_mul2[%d,%d]\n" ,arg,i); */
  tmp = &(in_mul2(arg,i));
  if (!tmp->computed) {
          tmp->value = ( arg-1>=0 && -arg+2>=0 && i-1>=0 && -i+N>=0 )  ? 
        ( compute_in_addmul1(arg+1,i) ) : 
       ( printf("? restriction error\n"), exit(-1));
     tmp->computed = 1;}
  return tmp->value;
}

static double compute_out_mul2(arg,i)
int arg,i;
{
  realvar *tmp;
/* printf("Computing: out_mul2[%d,%d]\n" ,arg,i); */
  tmp = &(out_mul2(arg,i));
  if (!tmp->computed) {
          tmp->value = compute_in_mul2(arg,i) * compute_in_mul2(arg+1,i);
     tmp->computed = 1;}
  return tmp->value;
}

static double compute_aux1_addmul1(arg,i)
int arg,i;
{
  realvar *tmp;
/* printf("Computing: aux1_addmul1[%d,%d]\n" ,arg,i); */
  tmp = &(aux1_addmul1(arg,i));
  if (!tmp->computed) {
          tmp->value = compute_out_mul2(arg,i);
     tmp->computed = 1;}
  return tmp->value;
}

static double compute_aux2_addmul1(arg,i)
int arg,i;
{
  realvar *tmp;
/* printf("Computing: aux2_addmul1[%d,%d]\n" ,arg,i); */
  tmp = &(aux2_addmul1(arg,i));
  if (!tmp->computed) {
     
          tmp->value = 
     ( arg-1==0 && i-1>=0 && -i+N>=0 )  ? ( compute_in_addmul1(arg,i) ) : 
         ( arg-2==0 && i-1>=0 && -i+N>=0 )  ? 
            ( compute_aux1_addmul1(arg-1,i) ) : 
         ( printf("? case error\n"), exit(-1));
     tmp->computed = 1;}
  return tmp->value;
}

static double compute_in_add3(arg,i)
int arg,i;
{
  realvar *tmp;
/* printf("Computing: in_add3[%d,%d]\n" ,arg,i); */
  tmp = &(in_add3(arg,i));
  if (!tmp->computed) {
          tmp->value = compute_aux2_addmul1(arg,i);
     tmp->computed = 1;}
  return tmp->value;
}

static double compute_out_add3(arg,i)
int arg,i;
{
  realvar *tmp;
/* printf("Computing: out_add3[%d,%d]\n" ,arg,i); */
  tmp = &(out_add3(arg,i));
  if (!tmp->computed) {
          tmp->value = compute_in_add3(arg,i) + compute_in_add3(arg+1,i);
     tmp->computed = 1;}
  return tmp->value;
}

static double compute_out_addmul1(arg,i)
int arg,i;
{
  realvar *tmp;
/* printf("Computing: out_addmul1[%d,%d]\n" ,arg,i); */
  tmp = &(out_addmul1(arg,i));
  if (!tmp->computed) {
          tmp->value = compute_out_add3(arg,i);
     tmp->computed = 1;}
  return tmp->value;
}

static double compute_aux1(arg,i)
int arg,i;
{
  realvar *tmp;
/* printf("Computing: aux1[%d,%d]\n" ,arg,i); */
  tmp = &(aux1(arg,i));
  if (!tmp->computed) {
          tmp->value = compute_out_addmul1(arg,i);
     tmp->computed = 1;}
  return tmp->value;
}

static double compute_aux2(arg,i)
int arg,i;
{
  realvar *tmp;
/* printf("Computing: aux2[%d,%d]\n" ,arg,i); */
  tmp = &(aux2(arg,i));
  if (!tmp->computed) {
          tmp->value = compute_aux1(arg,i-1);
     tmp->computed = 1;}
  return tmp->value;
}

static double compute_recinter(arg,i)
int arg,i;
{
  realvar *tmp;
/* printf("Computing: recinter[%d,%d]\n" ,arg,i); */
  tmp = &(recinter(arg,i));
  if (!tmp->computed) {
     
          tmp->value = 
     ( arg-1==0 && i-2>=0 && -i+N>=0 )  ? ( compute_aux2(arg,i) ) : 
       ( printf("? restriction error\n"), exit(-1));
     tmp->computed = 1;}
  return tmp->value;
}

static double compute_out(arg,i)
int arg,i;
{
  realvar *tmp;
/* printf("Computing: out[%d,%d]\n" ,arg,i); */
  tmp = &(out(arg,i));
  if (!tmp->computed) {
          tmp->value = ( arg-1==0 && i-N-1==0 )  ? ( compute_aux2(arg,i) ) : 
       ( printf("? restriction error\n"), exit(-1));
     tmp->computed = 1;}
  return tmp->value;
}

int main()
{
   int i, arg ;
   
   /* --inputs */
   for (arg=1; arg<=3; arg++)
   {  for (i=1; i<=min(5,4*arg-3); i++)
      {  printf("in[%d,%d]= %f\n", arg,i, compute_in(arg,i) );
      }
   }
   /* --outputs */
   /* arg:=1 */
   printf("out[%d,%d]= %f\n", 1,i, compute_out(1,i) );
}
