/* system MatMul */

/* C-Code generated by Alpha Code Generator version 1.2 */

#include <math.h>
typedef struct { int value;
		 int computed; } intvar;
typedef struct { int value;
		 int computed; } boolvar;
typedef struct { double value;
		 int computed; } realvar;
double atof();
int    atoi();

#define min(x,y) ((x)<(y)?(x):(y))
#define max(x,y) ((x)>(y)?(x):(y))
#define INFINITY 0x7fffffff
#define SHR(x,y) ((x)/(double)(1<<(y)))
#define SHL(x,y) ((x)*(double)(1<<(y)))
#define EXP(x,y) pow((x),(y))
#define TRUNCATE(x) ((int)(x))
#define CEILING(x) ((int)(ceil(x)))
#define FLOOR(x) ((int)(floor(x)))
#define ROUND(x) ((int)(rint(x)))
#define FLOAT(x) ((double)(x))

/* parameters */
#define N 4

/* input variables */
char __s_[32];
realvar __A[16];
#define A(i,j)	__A[(i)+4*(j)-5]
realvar __B[16];
#define B(i,j)	__B[(i)+4*(j)-5]

/* output variables */
realvar __C[16];
#define C(i,j)	__C[(i)+4*(j)-5]

/* local variables */
realvar __AccC[80];
#define AccC(i,j,k)	__AccC[(i)+4*(j)+16*(k)-5]

static double compute_A(i,j)
int i,j;
{
  realvar *tmp;
/* printf("Computing: A[%d,%d]\n" ,i,j); */
  tmp = &(A(i,j));
  if (!tmp->computed) {
          printf("Input A[%d,%d] =" ,i,j);
     gets(__s_);
     tmp->value = atof(__s_);
     tmp->computed = 1;}
  return tmp->value;
}

static double compute_B(i,j)
int i,j;
{
  realvar *tmp;
/* printf("Computing: B[%d,%d]\n" ,i,j); */
  tmp = &(B(i,j));
  if (!tmp->computed) {
          printf("Input B[%d,%d] =" ,i,j);
     gets(__s_);
     tmp->value = atof(__s_);
     tmp->computed = 1;}
  return tmp->value;
}

static double compute_C();

static double compute_AccC();

/* --let equations */
static double compute_AccC(i,j,k)
int i,j,k;
{
  realvar *tmp;
/* printf("Computing: AccC[%d,%d,%d]\n" ,i,j,k); */
  tmp = &(AccC(i,j,k));
  if (!tmp->computed) {
          tmp->value = ( k==0 )  ? ( 0 ) : 
         ( k-1>=0 )  ? 
            ( compute_AccC(i,j,k-1) + compute_A(i,k) * compute_B(k,j) ) : 
         ( printf("? case error\n"), exit(-1));
     tmp->computed = 1;}
  return tmp->value;
}

static double compute_C(i,j)
int i,j;
{
  realvar *tmp;
/* printf("Computing: C[%d,%d]\n" ,i,j); */
  tmp = &(C(i,j));
  if (!tmp->computed) {
          tmp->value = compute_AccC(i,j,N);
     tmp->computed = 1;}
  return tmp->value;
}

int main()
{
   int k, j, i ;
   
   /* --inputs */
   for (i=1; i<=N; i++)
   {  for (j=1; j<=N; j++)
      {  printf("A[%d,%d]= %f\n", i,j, compute_A(i,j) );
      }
   }
   for (i=1; i<=N; i++)
   {  for (j=1; j<=N; j++)
      {  printf("B[%d,%d]= %f\n", i,j, compute_B(i,j) );
      }
   }
   /* --outputs */
   for (i=1; i<=N; i++)
   {  for (j=1; j<=N; j++)
      {  printf("C[%d,%d]= %f\n", i,j, compute_C(i,j) );
      }
   }
}
