/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Thu Apr 24 10:21:53 1997
 */
#ifndef _writeitem_
#define _writeitem_
#if __STDC__

extern void print_item ( item *x );
extern void print_item_list ( item *x );

#else /* __STDC__ */

extern void print_item_list (/* item *x */);

#endif /* __STDC__ */
#endif /* _writeitem_ */
