/*
* generated by Xtext
*/
package fr.irisa.cairn.model.ui.contentassist;

import fr.irisa.cairn.model.ui.contentassist.AbstractMathematicaProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MathematicaProposalProvider extends AbstractMathematicaProposalProvider {

}
